### ISSUE TITLE
Add basic authentication options to configuration file

### ISSUE THREAD

**Issue by austenito** [austenito/ruby-resty#9]
Given the `~/.ruby_resty.yml` config file with username and password entries:

```
nyan:
  host: foo.com
  username: austen
  password: bar
  headers:
    header1: value
```

When the user starts resty with the `nyan` alias
Then every request includes the basic authentication info
